**PROJECT 2 : BioAgentGPT: A Multi-Agent Retrieval-Augmented Generation System for Cancer Biomarker and Pathway Research**

**1. Setup & Installation**

In [1]:
!pip -q install \
transformers \
sentence-transformers \
faiss-cpu \
langchain \
langchain-community \
langgraph \
biopython \
gradio \
pymupdf \
reportlab \
accelerate \
torch \
datasets

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.5/18.5 MB 107.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 109.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 126.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 25.7/25.7 MB 78.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 74.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 36.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.7/61.7 kB 4.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.1/73.1 kB 4.6 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires requests==2.32.4, but you have requests 2.34.2 which is incompatible.

**2. Imports & Environment Check**

In [1]:
import os
import torch
import gradio as gr

from Bio import Entrez

from transformers import pipeline
from sentence_transformers import SentenceTransformer

import faiss
import numpy as np

In [2]:
import torch

print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0))

True
Tesla T4

**3. NCBI Entrez configuration**

In [3]:
from Bio import Entrez

Entrez.email = "128013071@sastra.ac.in"

**4. Embedding Model Setup**

In [4]:
embedding_model = SentenceTransformer(
    "sentence-transformers/all-MiniLM-L6-v2"
)

print("Embedding model loaded.")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Embedding model loaded.

In [5]:
text = "Breast cancer biomarkers"

embedding = embedding_model.encode(text)

print(len(embedding))

384

In [6]:
dimension = 384

index = faiss.IndexFlatL2(dimension)

print(index.ntotal)

0

**5. FAISS Vector Store — Quick Demo**

In [7]:
texts = [
    "BRCA1 mutation causes breast cancer",
    "TP53 is a tumor suppressor",
    "HER2 is overexpressed in breast cancer"
]

vectors = embedding_model.encode(texts)

index.add(np.array(vectors).astype("float32"))

print(index.ntotal)

3

In [8]:
query = embedding_model.encode(
    ["breast cancer genes"]
)

D, I = index.search(
    np.array(query).astype("float32"),
    2
)

print(I)

[[0 2]]

In [9]:
for idx in I[0]:
    print(texts[idx])

BRCA1 mutation causes breast cancer
HER2 is overexpressed in breast cancer

In [10]:
print("Distances:")
print(D)

print("\nRetrieved Documents:")
for i, idx in enumerate(I[0]):
    print(f"\nResult {i+1}")
    print("Distance:", D[0][i])
    print("Document:", texts[idx])

Distances:
[[0.7719885 0.9290519]]

Retrieved Documents:

Result 1
Distance: 0.7719885
Document: BRCA1 mutation causes breast cancer

Result 2
Distance: 0.9290519
Document: HER2 is overexpressed in breast cancer

In [11]:
query = "tumor suppressor"

query_embedding = embedding_model.encode([query])

D, I = index.search(
    np.array(query_embedding).astype("float32"),
    2
)

print("Query:", query)

for idx in I[0]:
    print(texts[idx])

Query: tumor suppressor
TP53 is a tumor suppressor
HER2 is overexpressed in breast cancer

In [12]:
def search_documents(query, top_k=2):
    query_embedding = embedding_model.encode([query])

    D, I = index.search(
        np.array(query_embedding).astype("float32"),
        top_k
    )

    print(f"\nQuery: {query}\n")

    for rank, idx in enumerate(I[0], start=1):
        print(f"Result {rank}")
        print("Distance:", D[0][rank-1])
        print("Document:", texts[idx])
        print("-" * 40)

In [13]:
search_documents("HER2 breast cancer")

Query: HER2 breast cancer

Result 1
Distance: 0.26773268
Document: HER2 is overexpressed in breast cancer
----------------------------------------
Result 2
Distance: 1.1205091
Document: BRCA1 mutation causes breast cancer
----------------------------------------

**6. 6. PubMed Literature Retrieval**

In [14]:
from Bio import Entrez
from Bio import Medline
import pandas as pd

In [15]:
Entrez.email = "128013071@sastra.ac.in"

In [16]:
def search_pubmed(query, max_results=5):

    handle = Entrez.esearch(
        db="pubmed",
        term=query,
        retmax=max_results
    )

    results = Entrez.read(handle)
    handle.close()

    return results["IdList"]

In [17]:
pmids = search_pubmed("breast cancer biomarkers")

print(pmids)

['42400054', '42399903', '42399352', '42398129', '42397946']

In [18]:
def fetch_details(id_list):

    ids = ",".join(id_list)

    handle = Entrez.efetch(
        db="pubmed",
        id=ids,
        rettype="medline",
        retmode="text"
    )

    records = Medline.parse(handle)

    return list(records)

In [19]:
papers = fetch_details(pmids)

len(papers)

5

In [20]:
for paper in papers:

    print("="*80)

    print("Title:")
    print(paper.get("TI","No Title"))

    print("\nAuthors:")
    print(", ".join(paper.get("AU",[])))

    print("\nJournal:")
    print(paper.get("JT",""))

    print("\nYear:")
    print(paper.get("DP",""))

    print("\nAbstract:")
    print(paper.get("AB","No Abstract"))

    print()

================================================================================
Title:
Longitudinal evaluation of tumor-infiltrating lymphocyte scoring using automated region of interest registration in breast cancer.

Authors:
Fiorin A, Adalid-Llansa L, Reverte L, Sauras-Colon E, Gallardo-Borras N, Rashwan HA, Bosch-Princep R, Fischer-Carles A, Goyda E, Lejeune M, Mata-Cano D, Puig D, Sanchez-Alcantara T, Relloso Ortiz de Uriarte M, Llobera-Serentill M, Izuel-Navarro JA, Lopez-Pablo C

Journal:
Breast cancer research : BCR

Year:
2026 Jul 3

Abstract:
BACKGROUND: Tumor-infiltrating lymphocytes (TILs) are prognostic biomarkers in breast cancer (BC), particularly in HER2-positive and triple-negative subtypes. Assessment follows the international guidelines, in which pathologists evaluate whole hematoxylin and eosin (H&E)-stained slides while integrating representative regions of the invasive tumor. However, manual region selection can be labor-intensive, subjective, and may introduce variability, particularly across consecutive tissue sections. Automated region of interest (ROI) registration may mitigate this limitation, yet its impact on longitudinal TIL scoring has not been systematically evaluated. Here, we introduce three ROI registration strategies (direct, intermediate, and serial with/without quality control) and present an automated framework validated for consistent TIL scoring and clinical relevance in predicting relapse. METHODS: We analyzed 104 invasive BC cases, each with 12 consecutive H&E slides. A pathologist annotated ROIs on both the first and twelfth slides. We registered these ROIs using the proposed strategies. We then evaluated them with performance metrics, including Intersection over Union (IoU), Dice Similarity Coefficient (DSC), failure rate, and execution time. Two pathologists scored TILs on manual and automated ROIs. We assessed longitudinal consistency between the first manual ROI and the twelfth slide's corresponding ROIs. We also tested whether the association between TIL score and patient relapse outcomes was preserved. RESULTS: The direct registration strategy achieved the highest geometric accuracy (mean IoU = 0.650, DSC = 0.769), with < 1% failure rate and  approximately 5.8 s execution time. TIL scores for both manual and automated ROIs closely matched (P = 0.84), showing strong agreement (Spearman's rho = 0.923, ICC = 0.936, CCC = 0.915, Cohen's kappa = 0.786). Longitudinal analyses showed no significant variability across distant sections (P = 0.79 and P = 0.62). TIL concentrations differed significantly between patients with and without relapse, and this association was preserved on both the first and twelfth slides (P < 0.05). CONCLUSIONS: We present the first automated framework for longitudinal ROI registration to support TIL scoring in BC. By reducing manual effort and variability, the framework supports scalable evaluation of immune biomarkers across tissue depth while preserving clinically relevant signals, supporting precision immuno-oncology applications.

================================================================================
Title:
Plexin A2 regulated the metastasis in breast cancer through MCM7.

Authors:
Xiang C, Chen X, Mo F, Zhong Z, Wang Q, Kong D, Deng J, Hong M

Journal:
BMC cancer

Year:
2026 Jul 3

Abstract:
Breast cancer is a malignant tumour that affects women's health. In clinical practice, breast cancer is mainly treated by surgery, radiation, and drugs, but the risk of metastasis and recurrence is high, and metastasis is inextricably linked to the transcription and regulation of many molecule. In this manuscript, we first found 27 highly expressed genes and 58 lower expressed genes related to metastasis, then Plexin A2 was found highly expressed in the tissues from metastasis breast cancer and exerted as promote role in cell proliferation, migration, and invasion of MDA-MB-231. Also, CoIP-MS was used to detect the proteins which bind with Plexin A2 and differential expressed in highly metastasis MDA-MB-231 and 9 proteins were selected in highly invasion MDA-MB-231. Plexin A2 was found bind with MCM7 in a binding set of S45 through a phosphoserine/threonine binding group in highly metastasis MDA-MB-231. Moreover, Plexin A2 and MCM7 was found involved in cell proliferation, apoptosis inhibition, migration, and invasion of MDA-MB-231. In conclusion, Plexin A2 bind with MCM7 in a binding set of S45 through a phosphoserine/threonine binding group, Plexin A2 and MCM7 was involved in cell proliferation, apoptosis inhibition, migration, and invasion of MDA-MB-231. These results showed that Plexin A2 can be considered as a promising biomarker in breast cancer metastasis.

================================================================================
Title:
Integrating DNA methylation biomarkers for breast cancer risk prediction using artificial intelligence.

Authors:
Mahmoud NM, Mohamed A, Akram A, Ebrahim M, Awad A

Journal:
Scientific reports

Year:
2026 Jul 3

Abstract:
Breast cancer remains a major cause of morbidity and mortality among women worldwide, highlighting the necessity for predictive tools to identify at-risk individuals prior to the manifestation of symptoms. Standard imaging, like mammography, has limited sensitivity in dense breasts and relies on visible morphological changes. In contrast, circulating DNA methylation biomarkers provide a minimally invasive, stable alternative that detects systemic epigenetic changes before tumors develop. This study analyzes DNA methylation profiles from the GSE51032 EPIC-Italy cohort (Illumina HumanMethylation450K platform), involving 845 participants, including only 658 cancer-free and breast cancer samples. After quality control (QC), 224 pre-diagnostic breast cancer cases and 418 controls are included, totaling 642 samples across 483,848 CpG sites. Differential methylation analysis identifies 4621 CpG sites with significant methylation differences (FDR < 0.1, |Deltabeta| >= 0.03). These features are subsequently utilized to train and evaluate a variety of machine learning (ML) and deep learning (DL) classifiers. Among these, the random forest demonstrated the highest overall performance, attaining an area under the curve (AUC) of 0.849 and an accuracy of 0.798. These findings highlight the potential of integrating high-dimensional epigenomic biomarkers with artificial intelligence (AI) to enable early prediction of breast cancer risk, thereby promoting minimally invasive screening and personalized prevention strategies.

================================================================================
Title:
Antibody-drug conjugates beyond HER2: Translating evidence into practice for HR+ HER2-negative and triple-negative metastatic breast cancer.

Authors:
Gouveia MC, Freire PJG, Prado CGS, Leite CA, Zucchetti BM, Bonadio RC, Barrios C, Kahn A, Lustberg M, Barroso-Sousa R

Journal:
Breast (Edinburgh, Scotland)

Year:
2026 Jun 30

Abstract:
Antibody-drug conjugates (ADCs) have redefined therapeutic paradigms in metastatic breast cancer, offering unprecedented efficacy across hormone receptor-positive/HER2-negative and triple-negative subtypes. Trastuzumab deruxtecan, sacituzumab govitecan, datopotamab deruxtecan, and sacituzumab tirumotecan are expanding treatment options beyond traditional chemotherapy. As their clinical integration advances, optimizing the prevention and management of ADC-related toxicities, determining optimal sequencing strategies, and refining biomarker characterization have become central challenges. Ongoing research into ADC combinations, earlier-line use, and precision biomarker selection is expected to further reshape the therapeutic landscape and personalize care for patients with advanced breast cancer.

================================================================================
Title:
Integrating Participatory Social Innovation Into Requirements Engineering for AI Health Care Solutions: Case Study.

Authors:
Dantas C, Cabrita M, Bobowicz M, Op den Akker H, Rafael-Palou X, Hakkarainen T, Haavisto I, Strand F, Marti-Bonmati L, Divjak E, Ivanac G, Joshi S, Osuala R, Charalambous S, Tsirikoglou A, Ribas G, Diaz O, Carvalho AS, Costa E

Journal:
Journal of medical Internet research

Year:
2026 Jul 3

Abstract:
BACKGROUND: The successful design and implementation of artificial intelligence (AI)-driven solutions in health care requires early and continuous multidisciplinary and multiprofessional collaboration. However, diverse disciplinary educational backgrounds, varying languages, and cultural or geographic differences can lead to misunderstandings. To bridge this gap, a structured approach to AI requirements specification can facilitate a shared terminology and a deep mutual understanding among stakeholders, serving both as a guide for technological development and as a means of defining clear pathways for clinical implementation. While technical requirements are well-established in traditional technology development domains, this structured approach remains relatively underused within clinical and social science contexts. Consequently, valuable insights derived from participatory and stakeholder-driven approaches are often overlooked, limiting the relevance and trustworthiness of AI systems in health care settings. OBJECTIVE: This study presents a methodology for requirements gathering, specification, mapping, and verification, specifically engineered for the complex, multistakeholder environment of clinically applied AI. The methodology was implemented within the specific case of an international multidisciplinary project evaluating an AI-based prediction tool for neoadjuvant chemotherapy treatment response for breast cancer and forming a part of the developed AI validation framework. METHODS: The process for AI requirements gathering, specification, and monitoring included 3 iterative rounds of discussion, engaging nearly 150 social, clinical, technical, ethical, and regulatory experts and patients across Europe, South America, North Africa, and Eurasia. It combines established requirements engineering methods (including the MoSCoW [Must have, Should have, Could have, Will not have] framework) with social innovation techniques to ensure inclusivity and contextual relevance. RESULTS: A key finding is the successful development of a structured framework integrating participatory social innovation with formal requirements engineering in an international AI health care setting, through a traceable multisource workflow including clinical, ethical, and regulatory aspects. It is supplemented with an extensive list of 184 actionable consensus-based requirements, categorized by stakeholder group, providing valuable insights for AI researchers in the oncology field with the potential to be transferable to other digital health domains. The requirements align with the fairness, universality, traceability, usability, robustness, and explainability in the AI (FUTURE-AI) framework, ensuring the tool is trustworthy and comprehensive from a multistakeholder perspective, and ensuring comprehensive consideration of all elements of FUTURE-AI. CONCLUSIONS: The proposed methodology represents a significant advancement for requirements engineering in digital health by extending traditional technical processes to systematically incorporate nontechnical requirements from diverse global stakeholders. This unified approach is essential for ensuring AI solutions are not only technically robust but also clinically relevant, legally compliant, and socially acceptable.

In [21]:
paper_data = []

for paper in papers:

    paper_data.append({
        "Title": paper.get("TI",""),
        "Authors": ", ".join(paper.get("AU",[])),
        "Journal": paper.get("JT",""),
        "Year": paper.get("DP",""),
        "Abstract": paper.get("AB","")
    })

df = pd.DataFrame(paper_data)

df.head()

,Title,Authors,Journal,Year,Abstract
0,Longitudinal evaluation of tumor-infiltrating ...,"Fiorin A, Adalid-Llansa L, Reverte L, Sauras-C...",Breast cancer research : BCR,2026 Jul 3,BACKGROUND: Tumor-infiltrating lymphocytes (TI...
1,Plexin A2 regulated the metastasis in breast c...,"Xiang C, Chen X, Mo F, Zhong Z, Wang Q, Kong D...",BMC cancer,2026 Jul 3,Breast cancer is a malignant tumour that affec...
2,Integrating DNA methylation biomarkers for bre...,"Mahmoud NM, Mohamed A, Akram A, Ebrahim M, Awad A",Scientific reports,2026 Jul 3,Breast cancer remains a major cause of morbidi...
3,Antibody-drug conjugates beyond HER2: Translat...,"Gouveia MC, Freire PJG, Prado CGS, Leite CA, Z...","Breast (Edinburgh, Scotland)",2026 Jun 30,Antibody-drug conjugates (ADCs) have redefined...
4,Integrating Participatory Social Innovation In...,"Dantas C, Cabrita M, Bobowicz M, Op den Akker ...",Journal of medical Internet research,2026 Jul 3,BACKGROUND: The successful design and implemen...

In [22]:
df.to_csv("pubmed_papers.csv", index=False)

print("Saved!")

Saved!

In [23]:
df

,Title,Authors,Journal,Year,Abstract
0,Longitudinal evaluation of tumor-infiltrating ...,"Fiorin A, Adalid-Llansa L, Reverte L, Sauras-C...",Breast cancer research : BCR,2026 Jul 3,BACKGROUND: Tumor-infiltrating lymphocytes (TI...
1,Plexin A2 regulated the metastasis in breast c...,"Xiang C, Chen X, Mo F, Zhong Z, Wang Q, Kong D...",BMC cancer,2026 Jul 3,Breast cancer is a malignant tumour that affec...
2,Integrating DNA methylation biomarkers for bre...,"Mahmoud NM, Mohamed A, Akram A, Ebrahim M, Awad A",Scientific reports,2026 Jul 3,Breast cancer remains a major cause of morbidi...
3,Antibody-drug conjugates beyond HER2: Translat...,"Gouveia MC, Freire PJG, Prado CGS, Leite CA, Z...","Breast (Edinburgh, Scotland)",2026 Jun 30,Antibody-drug conjugates (ADCs) have redefined...
4,Integrating Participatory Social Innovation In...,"Dantas C, Cabrita M, Bobowicz M, Op den Akker ...",Journal of medical Internet research,2026 Jul 3,BACKGROUND: The successful design and implemen...

**7. Text Chunking and Preprocessing**

In [24]:
abstracts = df["Abstract"].tolist()

print(len(abstracts))

5

In [25]:
abstracts = [a for a in abstracts if isinstance(a, str) and len(a) > 50]

print("Valid abstracts:", len(abstracts))

Valid abstracts: 5

In [26]:
print(abstracts[0][:1000])

BACKGROUND: Tumor-infiltrating lymphocytes (TILs) are prognostic biomarkers in breast cancer (BC), particularly in HER2-positive and triple-negative subtypes. Assessment follows the international guidelines, in which pathologists evaluate whole hematoxylin and eosin (H&E)-stained slides while integrating representative regions of the invasive tumor. However, manual region selection can be labor-intensive, subjective, and may introduce variability, particularly across consecutive tissue sections. Automated region of interest (ROI) registration may mitigate this limitation, yet its impact on longitudinal TIL scoring has not been systematically evaluated. Here, we introduce three ROI registration strategies (direct, intermediate, and serial with/without quality control) and present an automated framework validated for consistent TIL scoring and clinical relevance in predicting relapse. METHODS: We analyzed 104 invasive BC cases, each with 12 consecutive H&E slides. A pathologist annotated

In [27]:
import os

os.makedirs("papers", exist_ok=True)

for i, abstract in enumerate(abstracts):

    with open(f"papers/paper_{i}.txt", "w", encoding="utf-8") as f:
        f.write(abstract)

print("All abstracts saved!")

All abstracts saved!

In [28]:
def split_text(text, chunk_size=500, overlap=100):

    chunks = []

    start = 0

    while start < len(text):

        end = start + chunk_size

        chunks.append(text[start:end])

        start += chunk_size - overlap

    return chunks

In [33]:
all_chunks = []

for abstract in abstracts:

    chunks = split_text(abstract)

    all_chunks.extend(chunks)

print("Total Chunks:", len(all_chunks))

Total Chunks: 27

In [34]:
print(all_chunks[0])

BACKGROUND: Tumor-infiltrating lymphocytes (TILs) are prognostic biomarkers in breast cancer (BC), particularly in HER2-positive and triple-negative subtypes. Assessment follows the international guidelines, in which pathologists evaluate whole hematoxylin and eosin (H&E)-stained slides while integrating representative regions of the invasive tumor. However, manual region selection can be labor-intensive, subjective, and may introduce variability, particularly across consecutive tissue sections.

**8. Building the RAG FAISS Index**

In [35]:
chunk_embeddings = embedding_model.encode(
    all_chunks,
    show_progress_bar=True
)

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

In [36]:
print(chunk_embeddings.shape)

(27, 384)

In [37]:
import faiss
import numpy as np

dimension = chunk_embeddings.shape[1]

rag_index = faiss.IndexFlatL2(dimension)

rag_index.add(
    np.array(chunk_embeddings).astype("float32")
)

print("Vectors Stored:", rag_index.ntotal)

Vectors Stored: 27

In [38]:
faiss.write_index(rag_index, "bioagent_index.faiss")

print("FAISS index saved.")

FAISS index saved.

In [39]:
import pickle

with open("chunks.pkl", "wb") as f:
    pickle.dump(all_chunks, f)

print("Chunks saved.")

Chunks saved.

**9. RAG Retrieval - Load and Test**

In [40]:
rag_index = faiss.read_index("bioagent_index.faiss")

with open("chunks.pkl", "rb") as f:
    all_chunks = pickle.load(f)

print("Index and chunks loaded.")

Index and chunks loaded.

In [41]:
def search_rag(query, top_k=3):

    query_embedding = embedding_model.encode([query])

    D, I = rag_index.search(
        np.array(query_embedding).astype("float32"),
        top_k
    )

    print(f"\nQuery: {query}\n")

    for rank, idx in enumerate(I[0], start=1):

        print("=" * 80)
        print(f"Result {rank}")
        print(f"Distance: {D[0][rank-1]:.4f}")
        print()
        print(all_chunks[idx])
        print()

In [42]:
search_rag("breast cancer biomarkers")

Query: breast cancer biomarkers

================================================================================
Result 1
Distance: 0.6545

Breast cancer remains a major cause of morbidity and mortality among women worldwide, highlighting the necessity for predictive tools to identify at-risk individuals prior to the manifestation of symptoms. Standard imaging, like mammography, has limited sensitivity in dense breasts and relies on visible morphological changes. In contrast, circulating DNA methylation biomarkers provide a minimally invasive, stable alternative that detects systemic epigenetic changes before tumors develop. This st

================================================================================
Result 2
Distance: 0.6968

 advances, optimizing the prevention and management of ADC-related toxicities, determining optimal sequencing strategies, and refining biomarker characterization have become central challenges. Ongoing research into ADC combinations, earlier-line use, and precision biomarker selection is expected to further reshape the therapeutic landscape and personalize care for patients with advanced breast cancer.

================================================================================
Result 3
Distance: 0.8080

ng an area under the curve (AUC) of 0.849 and an accuracy of 0.798. These findings highlight the potential of integrating high-dimensional epigenomic biomarkers with artificial intelligence (AI) to enable early prediction of breast cancer risk, thereby promoting minimally invasive screening and personalized prevention strategies.

In [43]:
search_rag("HER2 mutation")

Query: HER2 mutation

================================================================================
Result 1
Distance: 1.3758

Breast cancer is a malignant tumour that affects women's health. In clinical practice, breast cancer is mainly treated by surgery, radiation, and drugs, but the risk of metastasis and recurrence is high, and metastasis is inextricably linked to the transcription and regulation of many molecule. In this manuscript, we first found 27 highly expressed genes and 58 lower expressed genes related to metastasis, then Plexin A2 was found highly expressed in the tissues from metastasis breast cancer and

================================================================================
Result 2
Distance: 1.4951

astasis, then Plexin A2 was found highly expressed in the tissues from metastasis breast cancer and exerted as promote role in cell proliferation, migration, and invasion of MDA-MB-231. Also, CoIP-MS was used to detect the proteins which bind with Plexin A2 and differential expressed in highly metastasis MDA-MB-231 and 9 proteins were selected in highly invasion MDA-MB-231. Plexin A2 was found bind with MCM7 in a binding set of S45 through a phosphoserine/threonine binding group in highly metast

================================================================================
Result 3
Distance: 1.5563

l proliferation, apoptosis inhibition, migration, and invasion of MDA-MB-231. These results showed that Plexin A2 can be considered as a promising biomarker in breast cancer metastasis.

In [44]:
search_rag("AI for breast cancer diagnosis")

Query: AI for breast cancer diagnosis

================================================================================
Result 1
Distance: 0.5891

environment of clinically applied AI. The methodology was implemented within the specific case of an international multidisciplinary project evaluating an AI-based prediction tool for neoadjuvant chemotherapy treatment response for breast cancer and forming a part of the developed AI validation framework. METHODS: The process for AI requirements gathering, specification, and monitoring included 3 iterative rounds of discussion, engaging nearly 150 social, clinical, technical, ethical, and regula

================================================================================
Result 2
Distance: 0.8455

ng an area under the curve (AUC) of 0.849 and an accuracy of 0.798. These findings highlight the potential of integrating high-dimensional epigenomic biomarkers with artificial intelligence (AI) to enable early prediction of breast cancer risk, thereby promoting minimally invasive screening and personalized prevention strategies.

================================================================================
Result 3
Distance: 0.9081

orized by stakeholder group, providing valuable insights for AI researchers in the oncology field with the potential to be transferable to other digital health domains. The requirements align with the fairness, universality, traceability, usability, robustness, and explainability in the AI (FUTURE-AI) framework, ensuring the tool is trustworthy and comprehensive from a multistakeholder perspective, and ensuring comprehensive consideration of all elements of FUTURE-AI. CONCLUSIONS: The proposed m

In [45]:
search_rag("cell death pathways")

Query: cell death pathways

================================================================================
Result 1
Distance: 1.1385

d with MCM7 in a binding set of S45 through a phosphoserine/threonine binding group in highly metastasis MDA-MB-231. Moreover, Plexin A2 and MCM7 was found involved in cell proliferation, apoptosis inhibition, migration, and invasion of MDA-MB-231. In conclusion, Plexin A2 bind with MCM7 in a binding set of S45 through a phosphoserine/threonine binding group, Plexin A2 and MCM7 was involved in cell proliferation, apoptosis inhibition, migration, and invasion of MDA-MB-231. These results showed t

================================================================================
Result 2
Distance: 1.3811

l proliferation, apoptosis inhibition, migration, and invasion of MDA-MB-231. These results showed that Plexin A2 can be considered as a promising biomarker in breast cancer metastasis.

================================================================================
Result 3
Distance: 1.4003

astasis, then Plexin A2 was found highly expressed in the tissues from metastasis breast cancer and exerted as promote role in cell proliferation, migration, and invasion of MDA-MB-231. Also, CoIP-MS was used to detect the proteins which bind with Plexin A2 and differential expressed in highly metastasis MDA-MB-231 and 9 proteins were selected in highly invasion MDA-MB-231. Plexin A2 was found bind with MCM7 in a binding set of S45 through a phosphoserine/threonine binding group in highly metast

In [46]:
import os

print(os.listdir())

['.config', 'bioagent_index.faiss', 'papers', 'pubmed_papers.csv', 'chunks.pkl', 'sample_data']

**10. LLM Setup - Text Generation Model**

In [47]:
!pip -q install transformers accelerate sentencepiece

In [48]:
from huggingface_hub import login

login("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")

In [49]:
from transformers import AutoTokenizer, AutoModelForCausalLM
import torch

model_name = "Qwen/Qwen2.5-3B-Instruct"

tokenizer = AutoTokenizer.from_pretrained(model_name)

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    torch_dtype=torch.float16,
    device_map="auto"
)

print("Model loaded successfully!")

config.json:   0%|          | 0.00/661 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/7.30k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/2.78M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/1.67M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/7.03M [00:00<?, ?B/s]

[transformers] `torch_dtype` is deprecated! Use `dtype` instead!

model.safetensors.index.json:   0%|          | 0.00/35.6k [00:00<?, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/434 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/242 [00:00<?, ?B/s]

Model loaded successfully!

In [50]:
from transformers import pipeline

generator = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer
)

In [51]:
prompt = "Explain breast cancer biomarkers in simple terms."

output = generator(
    prompt,
    max_new_tokens=150,
    do_sample=False
)

print(output[0]["generated_text"])

[transformers] Passing `generation_config` together with generation-related arguments=({'max_new_tokens', 'do_sample'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.
[transformers] Both `max_new_tokens` (=150) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Ignoring clean_up_tokenization_spaces=True for BPE tokenizer Qwen2Tokenizer. The clean_up_tokenization post-processing step is designed for WordPiece tokenizers and is destructive for BPE (it strips spaces before punctuation). Set clean_up_tokenization_spaces=False to suppress this warning, or set clean_up_tokenization_spaces_for_bpe_even_though_it_will_corrupt_output=True to force cleanup anyway.

Explain breast cancer biomarkers in simple terms. Breast cancer biomarkers are special substances found in the blood or other body fluids that can help doctors understand if a person has breast cancer, how advanced it is, and what treatments might work best.

Think of them like clues to solve a mystery:

1. **Presence**: Some biomarkers show up when someone has breast cancer. It's like finding a fingerprint at a crime scene.
2. **Amount**: Others tell us how much cancer there is. It's like measuring how many fingerprints there are.
3. **Type**: Some biomarkers help identify different types of breast cancer. It's like figuring out which type of fingerprint it is.
4. **Response**: Others show how well a treatment works. It's like checking if the suspect was caught

In [52]:
from transformers import pipeline

generator = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    pad_token_id=tokenizer.eos_token_id
)

[transformers] Passing `generation_config` together with generation-related arguments=({'pad_token_id'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.

In [53]:
response = generator(
    "Explain BRCA1 mutation.",
    max_new_tokens=200,
    temperature=0.2,
    return_full_text=False
)

print(response[0]["generated_text"])

[transformers] Passing `generation_config` together with generation-related arguments=({'max_new_tokens', 'temperature'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.
[transformers] Both `max_new_tokens` (=200) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

 What are the symptoms of breast cancer in women with this mutation? How is it inherited?
BRCA1 (breast cancer susceptibility gene 1) is a tumor suppressor gene that plays a critical role in DNA repair, cell cycle regulation, and maintaining genomic stability. Mutations in the BRCA1 gene can lead to an increased risk of developing certain types of cancers, particularly breast and ovarian cancer.

Symptoms of breast cancer in women with a BRCA1 mutation may include:

1. Early onset of breast cancer: Women with BRCA1 mutations often develop breast cancer at a younger age than those without the mutation.
2. Multiple breast cancers: They may have multiple primary breast tumors or one large tumor with extensive involvement of both breasts.
3. Invasive ductal carcinoma: This is the most common type of breast cancer associated with BRCA1 mutations.
4. Invasive lobular carcinoma: Another common type of breast cancer linked to BRCA1 mutations.
5. Sarcomatoid

**11. RAG Pipeline - Context Retrieval and Prompt Construction**

In [54]:
import faiss

rag_index = faiss.read_index("bioagent_index.faiss")

print("FAISS index loaded.")

FAISS index loaded.

In [55]:
import pickle

with open("chunks.pkl", "rb") as f:
    all_chunks = pickle.load(f)

print("Chunks loaded.")
print("Total Chunks:", len(all_chunks))

Chunks loaded.
Total Chunks: 27

In [56]:
import numpy as np

def retrieve_documents(query, top_k=3):

    query_embedding = embedding_model.encode([query])

    distances, indices = rag_index.search(
        np.array(query_embedding).astype("float32"),
        top_k
    )

    retrieved_docs = []

    for idx in indices[0]:
        retrieved_docs.append(all_chunks[idx])

    return retrieved_docs

In [57]:
docs = retrieve_documents(
    "breast cancer biomarkers"
)

for i, doc in enumerate(docs):

    print("="*80)
    print(f"Document {i+1}\n")
    print(doc[:500])

================================================================================
Document 1

Breast cancer remains a major cause of morbidity and mortality among women worldwide, highlighting the necessity for predictive tools to identify at-risk individuals prior to the manifestation of symptoms. Standard imaging, like mammography, has limited sensitivity in dense breasts and relies on visible morphological changes. In contrast, circulating DNA methylation biomarkers provide a minimally invasive, stable alternative that detects systemic epigenetic changes before tumors develop. This st
================================================================================
Document 2

 advances, optimizing the prevention and management of ADC-related toxicities, determining optimal sequencing strategies, and refining biomarker characterization have become central challenges. Ongoing research into ADC combinations, earlier-line use, and precision biomarker selection is expected to further reshape the therapeutic landscape and personalize care for patients with advanced breast cancer.
================================================================================
Document 3

ng an area under the curve (AUC) of 0.849 and an accuracy of 0.798. These findings highlight the potential of integrating high-dimensional epigenomic biomarkers with artificial intelligence (AI) to enable early prediction of breast cancer risk, thereby promoting minimally invasive screening and personalized prevention strategies.

In [58]:
def build_context(query, top_k=3):

    docs = retrieve_documents(query, top_k)

    context = ""

    for i, doc in enumerate(docs, start=1):

        context += f"\n===== Research Paper {i} =====\n"
        context += doc
        context += "\n"

    return context

In [59]:
context = build_context("breast cancer biomarkers")

print(context[:2000])

===== Research Paper 1 =====
Breast cancer remains a major cause of morbidity and mortality among women worldwide, highlighting the necessity for predictive tools to identify at-risk individuals prior to the manifestation of symptoms. Standard imaging, like mammography, has limited sensitivity in dense breasts and relies on visible morphological changes. In contrast, circulating DNA methylation biomarkers provide a minimally invasive, stable alternative that detects systemic epigenetic changes before tumors develop. This st

===== Research Paper 2 =====
 advances, optimizing the prevention and management of ADC-related toxicities, determining optimal sequencing strategies, and refining biomarker characterization have become central challenges. Ongoing research into ADC combinations, earlier-line use, and precision biomarker selection is expected to further reshape the therapeutic landscape and personalize care for patients with advanced breast cancer.

===== Research Paper 3 =====
ng an area under the curve (AUC) of 0.849 and an accuracy of 0.798. These findings highlight the potential of integrating high-dimensional epigenomic biomarkers with artificial intelligence (AI) to enable early prediction of breast cancer risk, thereby promoting minimally invasive screening and personalized prevention strategies.

In [60]:
def create_prompt(query):

    context = build_context(query)

    prompt = f"""
You are BioAgentGPT, an expert biomedical AI research assistant.

Use ONLY the scientific literature provided below.

If the answer is not present in the literature,
say:
"I could not find sufficient evidence in the retrieved papers."

-----------------------------
Scientific Literature
-----------------------------

{context}

-----------------------------
User Question
-----------------------------

{query}

-----------------------------
Generate a scientific report with the following sections:

1. Executive Summary

2. Important Biomarkers

3. Key Findings

4. Clinical Significance

5. Future Research Directions

Answer in professional scientific language.
"""

    return prompt

In [61]:
prompt = create_prompt("breast cancer biomarkers")

print(prompt[:3000])

You are BioAgentGPT, an expert biomedical AI research assistant.

Use ONLY the scientific literature provided below.

If the answer is not present in the literature,
say:
"I could not find sufficient evidence in the retrieved papers."

-----------------------------
Scientific Literature
-----------------------------


===== Research Paper 1 =====
Breast cancer remains a major cause of morbidity and mortality among women worldwide, highlighting the necessity for predictive tools to identify at-risk individuals prior to the manifestation of symptoms. Standard imaging, like mammography, has limited sensitivity in dense breasts and relies on visible morphological changes. In contrast, circulating DNA methylation biomarkers provide a minimally invasive, stable alternative that detects systemic epigenetic changes before tumors develop. This st

===== Research Paper 2 =====
 advances, optimizing the prevention and management of ADC-related toxicities, determining optimal sequencing strategies, and refining biomarker characterization have become central challenges. Ongoing research into ADC combinations, earlier-line use, and precision biomarker selection is expected to further reshape the therapeutic landscape and personalize care for patients with advanced breast cancer.

===== Research Paper 3 =====
ng an area under the curve (AUC) of 0.849 and an accuracy of 0.798. These findings highlight the potential of integrating high-dimensional epigenomic biomarkers with artificial intelligence (AI) to enable early prediction of breast cancer risk, thereby promoting minimally invasive screening and personalized prevention strategies.


-----------------------------
User Question
-----------------------------

breast cancer biomarkers

-----------------------------
Generate a scientific report with the following sections:

1. Executive Summary

2. Important Biomarkers

3. Key Findings

4. Clinical Significance

5. Future Research Directions

Answer in professional scientific language.

**12. RAG Question Answering**

In [62]:
def ask_bioagent(query):

    prompt = create_prompt(query)

    response = generator(
        prompt,
        max_new_tokens=500,
        temperature=0.2,
        return_full_text=False
    )

    return response[0]["generated_text"]

In [63]:
answer = ask_bioagent("breast cancer biomarkers")

print(answer)

[transformers] Both `max_new_tokens` (=500) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

# Scientific Report

## Executive Summary

This report synthesizes recent advancements in breast cancer biomarkers, focusing on circulating DNA methylation biomarkers and epigenomic biomarkers integrated with artificial intelligence (AI). The studies reviewed underscore the utility of these biomarkers in detecting systemic epigenetic changes before tumor development, which can lead to improved early prediction of breast cancer risk. Additionally, the integration of high-dimensional epigenomic biomarkers with AI holds promise for enhancing the accuracy and sensitivity of predictive models, facilitating minimally invasive screening and personalized prevention strategies.

## Important Biomarkers

### Circulating DNA Methylation Biomarkers
Circulating DNA methylation biomarkers have been identified as a promising tool for early detection of breast cancer. They offer a minimally invasive approach compared to standard imaging methods such as mammography, which often struggle with visibility in dense breast tissue. These biomarkers reflect systemic epigenetic alterations that precede tumor formation, providing valuable information for risk stratification.

### Epigenomic Biomarkers Integrated with Artificial Intelligence (AI)
Epigenomic biomarkers, when combined with AI, demonstrate significant potential for improving the accuracy and predictive power of biomarker-based risk assessments. High-dimensional epigenomic profiles can capture complex patterns of gene expression and regulation, while AI algorithms facilitate the identification of meaningful biomarker signatures and their integration into predictive models.

## Key Findings

- **Research Paper 1** reported an AUC of 0.849 and an accuracy of 0.798 for a study involving high-dimensional epigenomic biomarkers. This indicates a strong predictive capability for identifying individuals at increased risk of breast cancer.
- **Research Paper 3** highlighted the integration of high-dimensional epigenomic biomarkers with AI, achieving an AUC of 0.849 and an accuracy of 0.798. These results underscore the potential of this approach in enhancing the reliability of predictive models.

## Clinical Significance

The clinical significance of these biomarkers lies in their ability to support early detection and personalized prevention strategies. By identifying individuals at higher risk, targeted interventions can be implemented to reduce the incidence and impact of breast cancer. Furthermore, the minimally invasive nature of circulating DNA methylation biomarkers makes them accessible for widespread screening programs, potentially leading to earlier diagnosis and improved patient outcomes.

## Future Research Directions

Future research should focus on validating these biomarkers across diverse populations and incorporating additional layers of complexity, such as genetic and environmental factors

In [64]:
print(ask_bioagent("What are breast cancer biomarkers?"))

[transformers] Both `max_new_tokens` (=500) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

-----------------------------
# Scientific Report

## Executive Summary
Breast cancer is a complex disease characterized by diverse molecular alterations that influence its diagnosis, prognosis, and treatment. Biomarkers play a crucial role in identifying high-risk individuals and guiding personalized treatment strategies. This report synthesizes key findings from recent studies to elucidate important biomarkers associated with breast cancer, including circulating DNA methylation biomarkers and gene expression profiles related to metastasis.

## Important Biomarkers
### Circulating DNA Methylation Biomarkers
Circulating DNA methylation biomarkers represent a promising avenue for early detection of breast cancer. These biomarkers are minimally invasive and can detect systemic epigenetic changes before visible morphological changes occur. They offer a stable alternative to conventional imaging methods such as mammography, which may be less effective in dense breast tissue.

### Gene Expression Profiles Related to Metastasis
Gene expression profiling has identified several genes that are differentially expressed in metastatic breast cancer compared to non-metastatic tumors. For instance, our study identified 27 highly expressed genes and 58 lower expressed genes related to metastasis. Among these, Plexin A2 was found to be significantly upregulated in metastatic breast cancer tissues.

## Key Findings
The key findings from the literature include:
- The development of circulating DNA methylation biomarkers as a minimally invasive tool for early detection of breast cancer.
- Identification of gene expression profiles associated with metastasis, particularly the upregulation of Plexin A2 in metastatic breast cancer tissues.

## Clinical Significance
The clinical significance of these biomarkers lies in their potential to improve patient stratification and guide personalized treatment strategies. Early detection through circulating DNA methylation biomarkers can facilitate timely intervention, potentially reducing morbidity and mortality. Additionally, understanding the molecular mechanisms underlying metastasis can inform the development of targeted therapies and combination treatments.

## Future Research Directions
Future research should focus on validating circulating DNA methylation biomarkers in larger cohorts and exploring their utility in clinical settings. Further investigation into the mechanisms by which Plexin A2 contributes to metastasis is warranted, as this knowledge could lead to the development of novel therapeutic targets. Additionally, integrating circulating DNA methylation biomarkers with gene expression profiles may enhance diagnostic accuracy and prognostic value.

---

I could not find sufficient evidence in the retrieved papers to directly address the question "What are breast cancer biomarkers?" However, the provided literature highlights circulating DNA methylation biomarkers and gene expression profiles as

In [65]:
print(ask_bioagent("Explain HER2 in breast cancer."))

[transformers] Both `max_new_tokens` (=500) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Scientific Report

1. Executive Summary
The executive summary provides a concise overview of the key points discussed in the document. It highlights the importance of understanding HER2 in breast cancer, the identification of important biomarkers, and the key findings regarding Plexin A2 and its role in metastasis and invasion.

2. Important Biomarkers
HER2 is a well-known oncogene overexpressed in approximately 20% of breast cancers, predominantly in the HER2-positive subtype. This overexpression is associated with aggressive disease, poor prognosis, and resistance to standard therapies. The presence of HER2 amplification or overexpression is crucial for the diagnosis and treatment decisions in breast cancer patients.

3. Key Findings
Plexin A2 has been identified as a critical factor in the progression of breast cancer, specifically in relation to metastasis and invasion. Research indicates that Plexin A2 is highly expressed in metastatic breast cancer tissues and plays a significant role in promoting cell proliferation, migration, and invasion. Further studies have revealed that Plexin A2 interacts with MCM7, a protein involved in DNA replication, suggesting a potential mechanism for its pro-metastatic activity. Additionally, Plexin A2 has been shown to interact with other proteins, including those involved in cell adhesion and signaling pathways, further emphasizing its multifaceted role in breast cancer progression.

4. Clinical Significance
Understanding the role of Plexin A2 in breast cancer metastasis and invasion has significant implications for clinical management. As Plexin A2 is highly expressed in metastatic breast cancer tissues, it represents a potential therapeutic target for the development of novel anti-metastatic strategies. Moreover, the identification of Plexin A2 as a key player in breast cancer progression underscores the importance of comprehensive molecular profiling in the evaluation of breast cancer patients. This information can aid in the stratification of patients into different therapeutic groups based on their molecular profiles, thereby improving treatment outcomes.

5. Future Research Directions
Future research should focus on elucidating the precise mechanisms by which Plexin A2 promotes metastasis and invasion. Investigating the interaction between Plexin A2 and other metastasis-related proteins will provide valuable insights into the underlying biological processes. Additionally, the development of targeted therapies against Plexin A2 could offer new avenues for treating breast cancer patients. Furthermore, the integration of Plexin A2 expression levels with other biomarkers, such as HER2 status, may help in predicting patient response to therapy and

In [66]:
print(ask_bioagent("How is artificial intelligence used in breast cancer diagnosis?"))

[transformers] Both `max_new_tokens` (=500) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

-----------------------------
Scientific Report

1. Executive Summary
The integration of artificial intelligence (AI) in the context of breast cancer diagnosis has been explored through various studies. This report synthesizes key findings from three research papers that discuss the application of AI in this domain. Specifically, it highlights the use of AI in predicting neoadjuvant chemotherapy treatment response and the integration of high-dimensional epigenomic biomarkers with AI for early prediction of breast cancer risk. The methodologies employed include iterative rounds of discussion involving stakeholders to ensure the AI tool's comprehensiveness and trustworthiness.

2. Important Biomarkers
High-dimensional epigenomic biomarkers have been identified as crucial in the development of AI tools for breast cancer diagnosis. These biomarkers provide a rich source of information that can be utilized by AI algorithms to predict breast cancer risk. Additionally, the use of epigenomic biomarkers alongside traditional genetic markers offers a more comprehensive approach to early detection and risk stratification.

3. Key Findings
- In Research Paper 1, an AI-based prediction tool for neoadjuvant chemotherapy treatment response for breast cancer was evaluated. The tool demonstrated an AUC of 0.849 and an accuracy of 0.798, indicating its potential for improving clinical outcomes.
- Research Paper 2 emphasizes the importance of high-dimensional epigenomic biomarkers in conjunction with AI for early prediction of breast cancer risk. This combination allows for the identification of individuals at higher risk, enabling targeted interventions and personalized prevention strategies.
- Research Paper 3 outlines the development of an AI tool for breast cancer diagnosis, which was informed by stakeholder groups. The tool adheres to the FUTURE-AI framework, ensuring fairness, universality, traceability, usability, robustness, and explainability, thus enhancing its reliability and trustworthiness.

4. Clinical Significance
The integration of AI in breast cancer diagnosis holds significant clinical implications. By leveraging AI, clinicians can achieve more accurate predictions of treatment response and risk stratification, leading to better patient outcomes. Early detection facilitated by AI can also reduce the need for invasive procedures, thereby minimizing patient discomfort and healthcare costs. Furthermore, personalized prevention strategies based on AI-generated risk assessments can empower patients to take proactive measures against breast cancer.

5. Future Research Directions
Future research should focus on refining AI models using larger and more diverse datasets to improve their predictive accuracy. Additionally, efforts should be made to validate AI tools across different populations and healthcare settings to ensure

**13. Planner Agent**

In [67]:
def planner_agent(query):

    query = query.lower()

    tasks = []

    if "gene" in query or "biomarker" in query:
        tasks.append("gene_search")

    if "pathway" in query:
        tasks.append("pathway_search")

    if "cancer" in query or "breast" in query:
        tasks.append("literature_search")

    tasks.append("rag_answer")

    return tasks

In [77]:
tasks = planner_agent("Find breast cancer biomarkers")

print(tasks)

['gene_search', 'literature_search', 'rag_answer']

In [68]:
tasks = planner_agent(
    "Explain HER2 signaling pathway"
)

print(tasks)

['pathway_search', 'rag_answer']

In [78]:
def execute_plan(query):

    tasks = planner_agent(query)

    print("Execution Plan")

    print("-"*40)

    for task in tasks:

        print(task)

    print("-"*40)

    return tasks

In [79]:
execute_plan("Find breast cancer biomarkers")

Execution Plan
----------------------------------------
gene_search
literature_search
rag_answer
----------------------------------------

['gene_search', 'literature_search', 'rag_answer']

**14. Literature Agent**

In [80]:
def literature_agent(query):

    print("Literature Agent Running...")

    docs = retrieve_documents(query)

    return docs

In [81]:
docs = literature_agent(
    "breast cancer biomarkers"
)

print(len(docs))

Literature Agent Running...
3

**15. Gene Extraction Agent**

In [82]:
GENES = [
    "BRCA1",
    "BRCA2",
    "HER2",
    "TP53",
    "EGFR",
    "PIK3CA",
    "ESR1",
    "AR",
    "PD-L1"
]

def gene_agent(documents):

    found = set()

    for doc in documents:

        text = doc.upper()

        for gene in GENES:

            if gene in text:

                found.add(gene)

    return sorted(found)

In [83]:
docs = retrieve_documents("breast cancer biomarkers")

genes = gene_agent(docs)

print(genes)

['AR']

**16. Pathway Mapping Agent**

In [84]:
PATHWAY_DB = {
    "BRCA1": [
        "Homologous Recombination",
        "DNA Damage Response"
    ],

    "BRCA2": [
        "Homologous Recombination",
        "DNA Damage Response"
    ],

    "HER2": [
        "PI3K-AKT Signaling",
        "MAPK Signaling"
    ],

    "TP53": [
        "p53 Signaling Pathway",
        "Cell Cycle"
    ],

    "EGFR": [
        "EGFR Signaling",
        "MAPK Signaling"
    ],

    "PIK3CA": [
        "PI3K-AKT Signaling"
    ],

    "ESR1": [
        "Estrogen Signaling"
    ],

    "AR": [
        "Androgen Receptor Signaling"
    ],

    "PD-L1": [
        "PD-1 Checkpoint Pathway"
    ]
}

In [85]:
def pathway_agent(gene_list):

    pathways = set()

    for gene in gene_list:

        if gene in PATHWAY_DB:

            pathways.update(PATHWAY_DB[gene])

    return sorted(pathways)

In [86]:
genes = ['AR', 'HER2', 'PD-L1']

pathways = pathway_agent(genes)

print(pathways)

['Androgen Receptor Signaling', 'MAPK Signaling', 'PD-1 Checkpoint Pathway', 'PI3K-AKT Signaling']

**17. Full Multi-Agent Workflow (Manual Orchestration)**

In [87]:
def bioagent_workflow(query):

    print("="*60)
    print("BioAgentGPT Workflow")
    print("="*60)

    tasks = planner_agent(query)

    print("\nExecution Plan:")
    print(tasks)

    docs = literature_agent(query)

    genes = gene_agent(docs)

    pathways = pathway_agent(genes)

    print("\nGenes Found:")
    print(genes)

    print("\nPathways Found:")
    print(pathways)

    answer = ask_bioagent(query)

    return {
        "documents": docs,
        "genes": genes,
        "pathways": pathways,
        "answer": answer
    }

In [88]:
result = bioagent_workflow(
    "Find breast cancer biomarkers"
)

[transformers] Both `max_new_tokens` (=500) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

============================================================
BioAgentGPT Workflow
============================================================

Execution Plan:
['gene_search', 'literature_search', 'rag_answer']
Literature Agent Running...

Genes Found:
['AR']

Pathways Found:
['Androgen Receptor Signaling']

In [89]:
print("="*80)
print("BioAgentGPT Scientific Report")
print("="*80)

print(result["answer"])

================================================================================
BioAgentGPT Scientific Report
================================================================================
-----------------------------

# Scientific Report

## Executive Summary

This report synthesizes recent research efforts aimed at identifying and characterizing biomarkers relevant to breast cancer. The studies reviewed underscore the importance of both traditional and emerging biomarkers in the context of early detection, personalized treatment, and risk stratification. Key findings include the utility of circulating DNA methylation biomarkers as minimally invasive alternatives to conventional imaging techniques, and the potential of integrating high-dimensional epigenomic biomarkers with artificial intelligence for early prediction of breast cancer risk.

## Important Biomarkers

### Traditional Biomarkers
- **Circulating Tumor DNA (ctDNA)**: A marker of tumor burden and response to therapy, often used in liquid biopsy settings.
- **Proteins**: Such as HER2, ER, PR, and Ki-67, which are commonly used in clinical practice for diagnosis and prognosis.
- **Immunohistochemistry (IHC)**: Utilized to assess the expression of biomarkers such as HER2, ER, and PR.

### Emerging Biomarkers
- **Circulating DNA Methylation Biomarkers**: These markers detect systemic epigenetic changes before tumors develop, providing a minimally invasive alternative to conventional imaging.
- **Epigenomic Biomarkers**: High-dimensional epigenomic profiles can be analyzed using next-generation sequencing technologies, offering insights into gene regulation and disease progression.

## Key Findings

The studies reviewed highlight the significant role of biomarkers in the field of breast cancer. Specifically, the integration of circulating DNA methylation biomarkers with artificial intelligence demonstrates promising results in early prediction of breast cancer risk. Additionally, the use of high-dimensional epigenomic biomarkers in combination with AI shows potential for enhancing the accuracy of risk stratification and personalized prevention strategies.

## Clinical Significance

The identification and validation of biomarkers offer substantial clinical benefits by enabling early detection, facilitating targeted therapies, and supporting personalized treatment plans. For instance, circulating DNA methylation biomarkers can serve as non-invasive alternatives to conventional imaging, potentially reducing patient discomfort and improving accessibility. Furthermore, the integration of epigenomic biomarkers with AI holds promise for developing more accurate risk prediction models, which can guide preventive measures and improve patient outcomes.

## Future Research Directions

Future research should focus on validating and expanding the application of emerging biomarkers, particularly circulating DNA methylation biomarkers and epigenomic biomarkers. Studies should explore the utility of these biomarkers in various clinical settings, including early detection, risk strat

In [90]:
print("\n" + "="*80)
print("Detected Genes")
print("="*80)

for gene in result["genes"]:
    print("•", gene)

print("\n" + "="*80)
print("Related Pathways")
print("="*80)

for pathway in result["pathways"]:
    print("•", pathway)

print("\n" + "="*80)
print("AI Generated Report")
print("="*80)

print(result["answer"])

================================================================================
Detected Genes
================================================================================
• AR

================================================================================
Related Pathways
================================================================================
• Androgen Receptor Signaling

================================================================================
AI Generated Report
================================================================================
-----------------------------

# Scientific Report

## Executive Summary

This report synthesizes recent research efforts aimed at identifying and characterizing biomarkers relevant to breast cancer. The studies reviewed underscore the importance of both traditional and emerging biomarkers in the context of early detection, personalized treatment, and risk stratification. Key findings include the utility of circulating DNA methylation biomarkers as minimally invasive alternatives to conventional imaging techniques, and the potential of integrating high-dimensional epigenomic biomarkers with artificial intelligence for early prediction of breast cancer risk.

## Important Biomarkers

### Traditional Biomarkers
- **Circulating Tumor DNA (ctDNA)**: A marker of tumor burden and response to therapy, often used in liquid biopsy settings.
- **Proteins**: Such as HER2, ER, PR, and Ki-67, which are commonly used in clinical practice for diagnosis and prognosis.
- **Immunohistochemistry (IHC)**: Utilized to assess the expression of biomarkers such as HER2, ER, and PR.

### Emerging Biomarkers
- **Circulating DNA Methylation Biomarkers**: These markers detect systemic epigenetic changes before tumors develop, providing a minimally invasive alternative to conventional imaging.
- **Epigenomic Biomarkers**: High-dimensional epigenomic profiles can be analyzed using next-generation sequencing technologies, offering insights into gene regulation and disease progression.

## Key Findings

The studies reviewed highlight the significant role of biomarkers in the field of breast cancer. Specifically, the integration of circulating DNA methylation biomarkers with artificial intelligence demonstrates promising results in early prediction of breast cancer risk. Additionally, the use of high-dimensional epigenomic biomarkers in combination with AI shows potential for enhancing the accuracy of risk stratification and personalized prevention strategies.

## Clinical Significance

The identification and validation of biomarkers offer substantial clinical benefits by enabling early detection, facilitating targeted therapies, and supporting personalized treatment plans. For instance, circulating DNA methylation biomarkers can serve as non-invasive alternatives to conventional imaging, potentially reducing patient discomfort and improving accessibility. Furthermore, the integration of epigenomic biomarkers with AI holds promise for developing more accurate risk prediction models, which can guide preventive measures and improve patient outcomes.

## Future Research Directions

Future research should focus on validating and expanding the application of emerging biomarkers, particularly circulating DNA methylation biomarkers and epigenomic biomarkers. Studies should explore the utility of these biomarkers in various clinical settings, including early detection, risk strat

In [91]:
#Modify generator
generator = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    pad_token_id=tokenizer.eos_token_id,
    return_full_text=False
)
response = generator(
    prompt,
    max_new_tokens=500,
    temperature=0.2,
    do_sample=False
)

[transformers] The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
[transformers] Passing `generation_config` together with generation-related arguments=({'max_new_tokens', 'do_sample', 'temperature'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.
[transformers] Both `max_new_tokens` (=500) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

**18. LangGraph State Machine**

In [92]:
!pip -q install langgraph

In [93]:
from typing import TypedDict
from langgraph.graph import StateGraph, END

In [ ]:
class BioState(TypedDict):

    query: str

    tasks: list

    documents: list

    genes: list

    pathways: list

    answer: str

In [94]:
def planner_node(state):

    state["tasks"] = planner_agent(
        state["query"]
    )

    return state

In [95]:
def literature_node(state):

    state["documents"] = literature_agent(
        state["query"]
    )

    return state

In [96]:
def gene_node(state):

    state["genes"] = gene_agent(
        state["documents"]
    )

    return state

In [97]:
def pathway_node(state):

    state["pathways"] = pathway_agent(
        state["genes"]
    )

    return state

In [98]:
def rag_node(state):

    state["answer"] = ask_bioagent(
        state["query"]
    )

    return state

In [102]:
from typing import TypedDict
from langgraph.graph import StateGraph, END

class BioState(TypedDict):
    query: str
    tasks: list
    documents: list
    genes: list
    pathways: list
    answer: str

workflow = StateGraph(BioState)

In [103]:
workflow.add_node(
    "planner",
    planner_node
)

workflow.add_node(
    "literature",
    literature_node
)

workflow.add_node(
    "gene",
    gene_node
)

workflow.add_node(
    "pathway",
    pathway_node
)

workflow.add_node(
    "rag",
    rag_node
)

In [104]:
workflow.set_entry_point("planner")

workflow.add_edge("planner", "literature")

workflow.add_edge("literature", "gene")

workflow.add_edge("gene", "pathway")

workflow.add_edge("pathway", "rag")

workflow.add_edge("rag", END)

In [105]:
graph = workflow.compile()

print("Graph Ready")

Graph Ready

In [106]:
result = graph.invoke(
    {
        "query":"Find breast cancer biomarkers"
    }
)

[transformers] Both `max_new_tokens` (=500) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Literature Agent Running...

In [107]:
print(result["genes"])

print(result["pathways"])

print(result["answer"])

['AR']
['Androgen Receptor Signaling']
-----------------------------

# Scientific Report

## Executive Summary

This report synthesizes current knowledge regarding biomarkers associated with breast cancer from the provided scientific literature. The analysis highlights key findings related to circulating DNA methylation biomarkers and their integration with artificial intelligence for early detection and personalized prevention strategies. Additionally, it underscores the importance of multidisciplinary approaches in identifying and managing adverse effects of antibody-drug conjugates (ADCs).

## Important Biomarkers

### Circulating DNA Methylation Biomarkers
Circulating DNA methylation biomarkers have been identified as promising candidates for early detection of breast cancer. These biomarkers are minimally invasive and can detect systemic epigenetic changes before tumors manifest clinically. They offer a complementary approach to traditional imaging methods such as mammography, which often lacks sensitivity in dense breast tissue.

### Artificial Intelligence (AI)
Artificial intelligence has shown significant promise in enhancing the predictive power of biomarkers by enabling the integration of high-dimensional epigenomic data. Machine learning algorithms can analyze complex patterns within these biomarkers to improve diagnostic accuracy and facilitate personalized risk stratification.

## Key Findings

- **Circulating DNA Methylation Biomarkers**: Studies have demonstrated that circulating DNA methylation profiles can be used to predict breast cancer risk with reasonable accuracy. For instance, one study reported an AUC of 0.849 and an accuracy of 0.798, indicating the potential utility of these biomarkers in early detection.

- **AI Integration**: The combination of circulating DNA methylation biomarkers with AI has shown enhanced predictive capabilities. This integration allows for the identification of subtle epigenetic alterations that may precede tumor development, thus facilitating early intervention and personalized prevention strategies.

## Clinical Significance

The clinical significance of these biomarkers lies in their ability to provide actionable information for both diagnosis and prevention. Early detection through circulating DNA methylation biomarkers can lead to timely interventions, potentially improving patient outcomes. Furthermore, the integration of AI enhances the reliability and personalization of these biomarkers, making them more effective tools for risk assessment and targeted therapy.

## Future Research Directions

Future research should focus on validating the clinical utility of circulating DNA methylation biomarkers across diverse populations and integrating these biomarkers with other non-invasive screening modalities. Additionally, there is a need to explore the feasibility of using these biomarkers in conjunction with ADCs to optimize treatment strategies and minimize toxicities. Further investigation into the underlying mechanisms of epigenetic changes and their relationship to

**19. Gradio Web App**

In [108]:
!pip -q install gradio

In [109]:
import gradio as gr

In [110]:
def bioagent_app(query):

    result = graph.invoke(
        {
            "query": query
        }
    )

    genes = ", ".join(result["genes"])

    pathways = ", ".join(result["pathways"])

    report = result["answer"]

    return genes, pathways, report

In [111]:
genes, pathways, report = bioagent_app(
    "Find breast cancer biomarkers"
)

print(genes)
print(pathways)
print(report[:500])

[transformers] Both `max_new_tokens` (=500) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Literature Agent Running...
AR
Androgen Receptor Signaling
-----------------------------
**Scientific Report**

**Executive Summary**
This report synthesizes the current state of knowledge regarding biomarkers for breast cancer, focusing on their clinical utility and future directions. The literature highlights the importance of identifying biomarkers that can predict breast cancer risk and aid in its early detection. Key findings include the use of circulating DNA methylation biomarkers as minimally invasive alternatives to standard imaging techniques.

In [112]:
demo = gr.Interface(
    fn=bioagent_app,

    inputs=gr.Textbox(
        lines=2,
        placeholder="Example: Find breast cancer biomarkers"
    ),

    outputs=[
        gr.Textbox(label="Detected Genes"),
        gr.Textbox(label="Related Pathways"),
        gr.Textbox(label="Scientific Report")
    ],

    title="🧬 BioAgentGPT",

    description="""
Autonomous AI Research Assistant

✔ PubMed Literature Search

✔ RAG

✔ Multi-Agent AI

✔ LLM

✔ Gene Discovery

✔ Pathway Analysis
"""
)

In [113]:
demo.launch(debug=True)

It looks like you are running Gradio on a hosted Jupyter notebook, which requires `share=True`. Automatically setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. This cell will run indefinitely so that you can see errors and logs. To turn off, set debug=False in launch().
* Running on public URL: https://e01b79e10f50c67e07.gradio.live

This share link is temporary and will last for up to 1 week (best effort). For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)

/usr/local/lib/python3.12/dist-packages/gradio/routes.py:1379: StarletteDeprecationWarning: 'HTTP_422_UNPROCESSABLE_ENTITY' is deprecated. Use 'HTTP_422_UNPROCESSABLE_CONTENT' instead.
  return await queue_join_helper(body, request, username)
[transformers] Both `max_new_tokens` (=500) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Literature Agent Running...
Keyboard interruption in main thread... closing server.
Killing tunnel 127.0.0.1:7860 <> https://e01b79e10f50c67e07.gradio.live

**Test Questions after click the link**

Find breast cancer biomarkers

Explain HER2 receptor

Role of androgen receptor

**any question regarding this**

**20. PDF Report Generation**

In [114]:
!pip -q install reportlab

In [115]:
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer
)

from reportlab.lib.styles import getSampleStyleSheet

from reportlab.lib.units import inch

from datetime import datetime

In [116]:
def generate_pdf(query, genes, pathways, report):

    filename = "BioAgentGPT_Report.pdf"

    doc = SimpleDocTemplate(filename)

    styles = getSampleStyleSheet()

    elements = []

    elements.append(
        Paragraph("<b>BioAgentGPT Research Report</b>", styles["Title"])
    )

    elements.append(Spacer(1, 0.3*inch))

    elements.append(
        Paragraph(
            f"<b>Date:</b> {datetime.now()}",
            styles["Normal"]
        )
    )

    elements.append(Spacer(1,0.2*inch))

    elements.append(
        Paragraph(
            f"<b>Research Question:</b> {query}",
            styles["Heading2"]
        )
    )

    elements.append(Spacer(1,0.2*inch))

    elements.append(
        Paragraph(
            f"<b>Detected Genes:</b> {genes}",
            styles["Normal"]
        )
    )

    elements.append(Spacer(1,0.2*inch))

    elements.append(
        Paragraph(
            f"<b>Related Pathways:</b> {pathways}",
            styles["Normal"]
        )
    )

    elements.append(Spacer(1,0.3*inch))

    elements.append(
        Paragraph(
            "<b>Scientific Report</b>",
            styles["Heading2"]
        )
    )

    elements.append(
        Paragraph(report.replace("\n","<br/>"),
                  styles["BodyText"])
    )

    doc.build(elements)

    return filename

In [117]:
pdf = generate_pdf(
    "Find breast cancer biomarkers",
    ", ".join(result["genes"]),
    ", ".join(result["pathways"]),
    result["answer"]
)

print(pdf)

BioAgentGPT_Report.pdf

In [118]:
from IPython.display import FileLink

FileLink("BioAgentGPT_Report.pdf")

/content/BioAgentGPT_Report.pdf

**21. Final App - Public Deployment**

In [119]:
def bioagent_app(query):

    result = graph.invoke({"query": query})

    genes = ", ".join(result["genes"])
    pathways = ", ".join(result["pathways"])
    report = result["answer"]

    pdf = generate_pdf(
        query,
        genes,
        pathways,
        report
    )

    return genes, pathways, report, pdf

In [120]:
demo = gr.Interface(
    fn=bioagent_app,

    inputs=gr.Textbox(
        lines=2,
        placeholder="Example: Find breast cancer biomarkers",
        label="Research Question"
    ),

    outputs=[
        gr.Textbox(label="Detected Genes"),
        gr.Textbox(label="Related Pathways"),
        gr.Textbox(label="Scientific Report"),
        gr.File(label="Download PDF Report")
    ],

    title="🧬 BioAgentGPT",

    description="""
Autonomous AI Research Assistant

✔ PubMed Literature Search
✔ Retrieval-Augmented Generation (RAG)
✔ Multi-Agent AI
✔ Gene Discovery
✔ Pathway Analysis
✔ PDF Report Generation
""",

    examples=[
        ["Find breast cancer biomarkers"],
        ["Explain HER2 receptor"],
        ["Role of BRCA1"],
        ["AI in breast cancer diagnosis"]
    ]
)

In [121]:
demo.launch(
    share=True,
    debug=True
)

Colab notebook detected. This cell will run indefinitely so that you can see errors and logs. To turn off, set debug=False in launch().
* Running on public URL: https://c1fa4bb9d2ad604446.gradio.live

This share link is temporary and will last for up to 1 week (best effort). For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)

/usr/local/lib/python3.12/dist-packages/gradio/routes.py:1379: StarletteDeprecationWarning: 'HTTP_422_UNPROCESSABLE_ENTITY' is deprecated. Use 'HTTP_422_UNPROCESSABLE_CONTENT' instead.
  return await queue_join_helper(body, request, username)
[transformers] Both `max_new_tokens` (=500) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Literature Agent Running...
Keyboard interruption in main thread... closing server.
Killing tunnel 127.0.0.1:7860 <> https://c1fa4bb9d2ad604446.gradio.live